version: '3.8'

services:
  web:
    # Menggunakan Dockerfile yang sudah ada (Pastikan sudah dimodifikasi, lihat bagian 2)
    build: .
    
    # Port 8080 di host Anda akan mengarah ke port 80 di container web.
    ports:
      - "8080:80"  # Akses aplikasi di http://localhost:8080
      
    # Mounting folder saat ini ke direktori web server
    volumes:
      - .:/var/www/html
      
    # Menghapus 'depends_on: - db' karena tidak ada lagi layanan db lokal.

# Menghapus layanan 'db' dan volume 'db_data'